# jekyll configuration
title: Contract Shark
heading: a lightweight, open source framework for testing smart contracts and economic threats
logo: /assets/logo.svg
email: sam@freighttrust.com
google_analytics:

menu:
  - url: "#contractshark-framework"
    title: What is Contract Shark
  - url: "#installation"
    title: Getting started

remote_theme: evoprotocol/jekyll-theme
plugins:
  - jekyll-remote-theme
